@startuml

entity Vets {
  +id: INT
  +first_name: TEXT
  +last_name: TEXT
}

entity Specialties {
  +id: INT
  +name: TEXT
}

entity VetSpecialties {
  +vet_id: INT
  +specialty_id: INT
}

entity Types {
  +id: INT
  +name: TEXT
}

entity Owners {
  +id: INT
  +first_name: TEXT
  +last_name: TEXT
  +address: TEXT
  +city: TEXT
  +telephone: TEXT
}

entity Pets {
  +id: INT
  +name: TEXT
  +birth_date: DATE
  +type_id: INT
  +owner_id: INT
}

entity Visits {
  +id: INT
  +pet_id: INT
  +visit_date: DATE
  +description: TEXT
}

Vets ||--o{ VetSpecialties : has
Specialties ||--o{ VetSpecialties : has
Pets ||--o{ Visits : has

@enduml
