apiVersion: v1
kind: Service
metadata:
  name: demo-db
spec:
  ports:
    - port: 5432
  selector:
    app: demo-db

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-db
  labels:
    app: demo-db
spec:
  replicas: 1  # Ensure you have a replica for high availability
  selector:
    matchLabels:
      app: demo-db
  template:
    metadata:
      labels:
        app: demo-db
    spec:
      containers:
        - image: postgres:17
          name: postgresql
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: demo-db-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: demo-db-secret
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: demo-db-secret
                  key: database
          ports:
            - containerPort: 5432
              name: postgresql
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 5432
              initialDelaySeconds: 30
              periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 5432
              initialDelaySeconds: 30
              periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: postgresql
              initialDelaySeconds: 10
              periodSeconds: 10